name: Running Multiline Commands in Runner.
run-name: ${{ github.actor }} is testing multiline commands in the ubuntu runner 🚀
on: [push,workflow_dispatch]
jobs:
  build:
  name: Multiline Commands Runner Evaluation.
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Write a multi-line message
    run: |
      echo This demo file shows a 
      echo very basic and easy-to-understand workflow.